/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniWord;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juju
 */
public class miniWord extends javax.swing.JFrame {
    PersonalFile file = new PersonalFile();
    /**
     * Creates new form miniWord
     */
    public miniWord() {
        initComponents();
        this.setSize(834, 670);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        JPestañas.setEnabledAt(0, false);
        JPestañas.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPestañas = new javax.swing.JTabbedPane();
        PNArchivo = new javax.swing.JPanel();
        JPG1_selectNewFIle = new javax.swing.JLabel();
        JPG1_SelectFIle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPN1Next = new javax.swing.JLabel();
        PNEdi = new javax.swing.JPanel();
        JPG2_decript = new javax.swing.JLabel();
        JPG2_cript = new javax.swing.JLabel();
        JPG2_saveAs = new javax.swing.JLabel();
        JPG2_combo = new javax.swing.JComboBox<>();
        JPG2_save = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JPG2_area = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPN1FileName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(209, 213, 232));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Z003", 2, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Sample JUJU");

        JPestañas.setBackground(new java.awt.Color(30, 30, 30));
        JPestañas.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        JPestañas.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        JPestañas.setInheritsPopupMenu(true);

        PNArchivo.setBackground(new java.awt.Color(23, 23, 23));
        PNArchivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPG1_selectNewFIle.setBackground(new java.awt.Color(51, 51, 51));
        JPG1_selectNewFIle.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 18)); // NOI18N
        JPG1_selectNewFIle.setForeground(new java.awt.Color(38, 202, 247));
        JPG1_selectNewFIle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPG1_selectNewFIle.setText("Archivo nuevo");
        JPG1_selectNewFIle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 202, 247)));
        JPG1_selectNewFIle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPG1_selectNewFIle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPG1_selectNewFIleCLICKNO(evt);
            }
        });
        PNArchivo.add(JPG1_selectNewFIle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 40));

        JPG1_SelectFIle.setBackground(new java.awt.Color(51, 51, 51));
        JPG1_SelectFIle.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 18)); // NOI18N
        JPG1_SelectFIle.setForeground(new java.awt.Color(153, 153, 255));
        JPG1_SelectFIle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPG1_SelectFIle.setText("Elegir un archivo");
        JPG1_SelectFIle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        JPG1_SelectFIle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPG1_SelectFIle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPG1_SelectFIleCLICKNO(evt);
            }
        });
        PNArchivo.add(JPG1_SelectFIle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/juju/Documentos/JAVA/java-1/src/miniWord/1.png")); // NOI18N
        PNArchivo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        JPN1Next.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        JPN1Next.setForeground(new java.awt.Color(153, 153, 255));
        JPN1Next.setText("Continuar...");
        JPN1Next.setEnabled(false);
        JPN1Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPN1NextMouseClicked(evt);
            }
        });
        PNArchivo.add(JPN1Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        JPestañas.addTab("Archivo", PNArchivo);

        PNEdi.setBackground(new java.awt.Color(23, 23, 23));

        JPG2_decript.setBackground(new java.awt.Color(51, 51, 51));
        JPG2_decript.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 18)); // NOI18N
        JPG2_decript.setForeground(new java.awt.Color(38, 202, 247));
        JPG2_decript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPG2_decript.setText("Descifrar 🔓");
        JPG2_decript.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 202, 247)));
        JPG2_decript.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPG2_decript.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPG2_decriptCLICKNO(evt);
            }
        });

        JPG2_cript.setBackground(new java.awt.Color(51, 51, 51));
        JPG2_cript.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 18)); // NOI18N
        JPG2_cript.setForeground(new java.awt.Color(153, 153, 255));
        JPG2_cript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPG2_cript.setText("Cifrar 🔒");
        JPG2_cript.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        JPG2_cript.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPG2_cript.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPG2_criptCLICKNO(evt);
            }
        });

        JPG2_saveAs.setBackground(new java.awt.Color(51, 51, 51));
        JPG2_saveAs.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 18)); // NOI18N
        JPG2_saveAs.setForeground(new java.awt.Color(204, 102, 255));
        JPG2_saveAs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPG2_saveAs.setText("Copia nueva 📄📄");
        JPG2_saveAs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 255)));
        JPG2_saveAs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPG2_saveAs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPG2_saveAsCLICKNO(evt);
            }
        });

        JPG2_combo.setBackground(new java.awt.Color(30, 30, 30));
        JPG2_combo.setForeground(new java.awt.Color(204, 204, 204));
        JPG2_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RC2", "RC4", "Blowfish" }));
        JPG2_combo.setAlignmentX(0.9F);
        JPG2_combo.setAlignmentY(0.9F);

        JPG2_save.setBackground(new java.awt.Color(51, 51, 51));
        JPG2_save.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 18)); // NOI18N
        JPG2_save.setForeground(new java.awt.Color(102, 153, 255));
        JPG2_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPG2_save.setText("Guardar 🛟🛟🛟");
        JPG2_save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        JPG2_save.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPG2_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPG2_saveCLICKNO(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Serif CJK SC Medium", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("←");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        JPG2_area.setBackground(new java.awt.Color(23, 23, 23));
        JPG2_area.setColumns(20);
        JPG2_area.setForeground(new java.awt.Color(204, 204, 204));
        JPG2_area.setLineWrap(true);
        JPG2_area.setRows(5);
        JPG2_area.setWrapStyleWord(true);
        jScrollPane2.setViewportView(JPG2_area);

        javax.swing.GroupLayout PNEdiLayout = new javax.swing.GroupLayout(PNEdi);
        PNEdi.setLayout(PNEdiLayout);
        PNEdiLayout.setHorizontalGroup(
            PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNEdiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JPG2_cript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPG2_decript, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addComponent(JPG2_saveAs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(JPG2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JPG2_save, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        PNEdiLayout.setVerticalGroup(
            PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNEdiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PNEdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNEdiLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(PNEdiLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPG2_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(JPG2_saveAs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(JPG2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(JPG2_cript, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(JPG2_decript, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        JPestañas.addTab("Edición", PNEdi);

        jLabel4.setBackground(new java.awt.Color(224, 208, 238));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 202, 247));
        jLabel4.setText("MINI WORD");

        jLabel8.setFont(new java.awt.Font("SansSerif.plain", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("󰣇");

        jLabel7.setBackground(new java.awt.Color(255, 153, 153));
        jLabel7.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setText("▪");

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 202, 247));
        jLabel9.setText("▪");

        jLabel3.setBackground(new java.awt.Color(204, 102, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 255));
        jLabel3.setText("▪");

        JPN1FileName.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        JPN1FileName.setForeground(new java.awt.Color(153, 153, 255));
        JPN1FileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(JPN1FileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(JPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JPN1FileName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(JPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPestañas.getAccessibleContext().setAccessibleName("Archivo");

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPG1_SelectFIleCLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPG1_SelectFIleCLICKNO
        boolean selected = this.file.selectFile();
        if(!selected) return;
        JPN1FileName.setText(this.file.getFile().getName());
        JPN1Next.setEnabled(true);
    }//GEN-LAST:event_JPG1_SelectFIleCLICKNO

    private void JPG1_selectNewFIleCLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPG1_selectNewFIleCLICKNO
        this.file.saveAs("");
        if(this.file.getFile() == null) return;
        JPN1FileName.setText(this.file.getFile().getName());
        JPN1Next.setEnabled(true);
    }//GEN-LAST:event_JPG1_selectNewFIleCLICKNO

    private void JPN1NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN1NextMouseClicked
        JPestañas.setSelectedIndex(1);
        String text = this.file.readFile(this.file.getCurrentPath());
        JPG2_area.setText(text);
    }//GEN-LAST:event_JPN1NextMouseClicked

    private void JPG2_decriptCLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPG2_decriptCLICKNO
        String text = JPG2_area.getText().trim();
        String combo = (String) JPG2_combo.getSelectedItem();
        String newText = "";
        try {
            newText = PersonalFile.decriptContent("jujuKeyPrivate", combo, text);
            JPG2_area.setText(newText);
        } catch (Exception ex) {            
            JOptionPane.showMessageDialog(null, "Error al desencriptar");
        }
    }//GEN-LAST:event_JPG2_decriptCLICKNO

    private void JPG2_criptCLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPG2_criptCLICKNO
        String combo = (String) JPG2_combo.getSelectedItem();
        try {
            String text = JPG2_area.getText().trim();
            String newText = PersonalFile.encriptContent("jujuKeyPrivate", combo, text); 
            JPG2_area.setText(newText);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al encriptar");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_JPG2_criptCLICKNO

    private void JPG2_saveAsCLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPG2_saveAsCLICKNO
        String text = JPG2_area.getText().trim();
        this.file.saveAs(text);
        JOptionPane.showMessageDialog(null, "Guardado");
    }//GEN-LAST:event_JPG2_saveAsCLICKNO

    private void JPG2_saveCLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPG2_saveCLICKNO
        try {
            String text = JPG2_area.getText().trim();
            this.file.writeFile(this.file.getFile(), text);
            JOptionPane.showMessageDialog(null, "Guardado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_JPG2_saveCLICKNO

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JPestañas.setSelectedIndex(0);
        JPG2_area.setText("");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miniWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miniWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miniWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miniWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miniWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JPG1_SelectFIle;
    private javax.swing.JLabel JPG1_selectNewFIle;
    private javax.swing.JTextArea JPG2_area;
    private javax.swing.JComboBox<String> JPG2_combo;
    private javax.swing.JLabel JPG2_cript;
    private javax.swing.JLabel JPG2_decript;
    private javax.swing.JLabel JPG2_save;
    private javax.swing.JLabel JPG2_saveAs;
    private javax.swing.JLabel JPN1FileName;
    private javax.swing.JLabel JPN1Next;
    private javax.swing.JTabbedPane JPestañas;
    private javax.swing.JPanel PNArchivo;
    private javax.swing.JPanel PNEdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
