/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package S11;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juju
 */
public class n1 extends javax.swing.JFrame {

    /**
     * Creates new form n1
     */
    public n1() {
        initComponents();
        this.setResizable(false);
        String[][] matrix = new String[12][12];

        int[][] validations = this.pocoyo();

        String character = "";
        for (int i = 0; i < matrix.length; i++) {
            String line = "";
            for (int j = 0; j < matrix[i].length; j++) {
                boolean isValid = false;
                for (int[] validation : validations) {
                    if (i == validation[0] && j == validation[1]) {
                        isValid = true;
                        break;
                    }
                }
                if (isValid) {
                    line += "██";
                    continue;
                }
                line +=  "  ";
            }
            character += "-" + line + "\n";
        }
        System.out.println("\n" + character);
        jArea.setText("\n" + character);
        
        Timer timer;
        timer = new Timer(50, new ActionListener() {
            //String txtArea = prevTxt;
            @Override
            public void actionPerformed(ActionEvent e) {
                String moveTxt = "";
                moveTxt += "-" + jArea.getText().replaceAll("-", " -");
                
                
                if (jArea.getText().compareToIgnoreCase("-") > 1224) { 
                    moveTxt = moveTxt.replaceAll("-", "");
                    //moveTxt += jArea.getText().replaceAll(" ", "");
                    System.out.println(jArea.getText().compareToIgnoreCase("-") > 1224);
                }
                System.err.println(moveTxt);
                jArea.setText(moveTxt);

            }
        });

        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("SansSerif.plain", 1, 20)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setText("num1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jArea.setBackground(new java.awt.Color(51, 51, 51));
        jArea.setColumns(20);
        jArea.setRows(5);
        jScrollPane2.setViewportView(jArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jToggleButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    private int[][] pocoyo() {
        int[][] validations = {
            {0, 2},
            {0, 3},
            {1, 1},
            {1, 2},
            {1, 3},
            {1, 4},
            {1, 5},
            {2, 1},
            {2, 2},
            {2, 4},
            {2, 5},
            {3, 1},
            {3, 2},
            {3, 3},
            {3, 4},
            {3, 5},
            {3, 6},
            {4, 1},
            {4, 2},
            {4, 3},
            {4, 4},
            {4, 5},
            {5, 0},
            {5, 1},
            {5, 2},
            {5, 3},
            {5, 4},
            {5, 5},
            {5, 6},
            {6, 0},
            {6, 1},
            {6, 2},
            {6, 3},
            {6, 4},
            {6, 5},
            {6, 6},
            {7, 0},
            {7, 1},
            {7, 2},
            {7, 3},
            {7, 4},
            {7, 5},
            {7, 6},
            {8, 1},
            {8, 2},
            {8, 3},
            {8, 4},
            {8, 5},
            {9, 0},
            {9, 1},
            {9, 2},
            {9, 4},
            {9, 5},
            {9, 6},};
        return validations;
        //x 0 1 2 3 4 5 6
        //0    █████
        //1   █████████
        //2   ████  ████
        //3   ███████████
        //4   █████████
        //5 █████████████
        //6 █████████████
        //7 █████████████
        //8   █████████
        //9 █████   ███
    }

    private void displayMatrixInTable(String[][] matrix, JTable table) {
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[i].length; j++) {
                table.setValueAt(matrix[i][j], i, j);
            }
        }
    }

    private int getRadomNumber() {
        int max = 9;
        int min = 1;
        return (int) Math.floor(Math.random() * (max - min + 1) + min);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
