/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package S10;

import s09.*;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/*
 *
 * @author juju
 */
public class Numero2 extends javax.swing.JFrame {

    /**
     * Creates new form arreglos
     */
    public Numero2() {
        initComponents();
        this.setResizable(false);
        this.setSize(1011, 860);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCombo1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JlabelRotate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Fire = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JListA = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        JListRes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        JListB = new javax.swing.JList<>();

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("DejaVu Sans Light", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Resetear");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(25, 25, 25));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCombo1.setBackground(new java.awt.Color(0, 0, 0));
        jCombo1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jCombo1.setForeground(new java.awt.Color(204, 204, 204));
        jCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 164, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ETC");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setText("▪");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, 17));

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setText("▪");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, 17));

        jLabel2.setBackground(new java.awt.Color(204, 102, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 255));
        jLabel2.setText("▪");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 17));

        JlabelRotate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JlabelRotate.setForeground(new java.awt.Color(204, 204, 204));
        JlabelRotate.setText("TPG - S11");
        JlabelRotate.setToolTipText("");
        JlabelRotate.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JlabelRotate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JlabelRotate.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel4.add(JlabelRotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("NO");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLICKNO(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 70, 90));

        jLabel7.setFont(new java.awt.Font("Cartograph CF Heavy", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 153, 255));
        jLabel7.setText("GO");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLICKGO(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, 90));

        jLabel8.setFont(new java.awt.Font("SansSerif.plain", 1, 110)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("󰣇");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 120));

        jLabel9.setFont(new java.awt.Font("Z003", 2, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Sample JUJU");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 860));

        Fire.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Z003", 2, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Sample JUJU");

        label.setFont(new java.awt.Font("SansSerif.plain", 0, 48)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("");

        javax.swing.GroupLayout FireLayout = new javax.swing.GroupLayout(Fire);
        Fire.setLayout(FireLayout);
        FireLayout.setHorizontalGroup(
            FireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FireLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
            .addGroup(FireLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FireLayout.setVerticalGroup(
            FireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FireLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(label)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        jPanel1.add(Fire, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 240, 200));

        jScrollPane5.setBackground(new java.awt.Color(51, 51, 51));

        JListA.setBackground(new java.awt.Color(51, 51, 51));
        JListA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador A", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Light", 0, 21), new java.awt.Color(204, 204, 204))); // NOI18N
        JListA.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JListA.setForeground(new java.awt.Color(153, 153, 255));
        JListA.setEnabled(false);
        JListA.setFocusable(false);
        JListA.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane5.setViewportView(JListA);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 240, 590));

        jScrollPane6.setBackground(new java.awt.Color(51, 51, 51));

        JListRes.setBackground(new java.awt.Color(51, 51, 51));
        JListRes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados por partida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Light", 0, 21), new java.awt.Color(204, 204, 204))); // NOI18N
        JListRes.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JListRes.setForeground(new java.awt.Color(153, 153, 255));
        JListRes.setEnabled(false);
        JListRes.setFocusable(false);
        JListRes.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane6.setViewportView(JListRes);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 240, 590));

        jArea.setEditable(false);
        jArea.setBackground(new java.awt.Color(22, 22, 22));
        jArea.setColumns(10);
        jArea.setFont(new java.awt.Font("DejaVu Sans", 0, 21)); // NOI18N
        jArea.setForeground(new java.awt.Color(153, 153, 153));
        jArea.setRows(5);
        jArea.setAutoscrolls(false);
        jArea.setFocusable(false);
        jArea.setPreferredSize(new java.awt.Dimension(216, 200));
        jArea.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(jArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 520, 210));

        jScrollPane7.setBackground(new java.awt.Color(51, 51, 51));

        JListB.setBackground(new java.awt.Color(51, 51, 51));
        JListB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador B", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Light", 0, 21), new java.awt.Color(204, 204, 204))); // NOI18N
        JListB.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JListB.setForeground(new java.awt.Color(153, 153, 255));
        JListB.setEnabled(false);
        JListB.setFocusable(false);
        JListB.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane7.setViewportView(JListB);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 240, 590));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLICKGO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLICKGO

        try {
            DefaultListModel modelA = new DefaultListModel();
            DefaultListModel modelB = new DefaultListModel();
            DefaultListModel modelResultado = new DefaultListModel();

            int CantidadganadorA = 0;
            int CantidadganadorB = 0;
            int randomSumaEmpate = 0;

            for (int i = 0; i < 20; i++) {
                String randomUnionA = "";
                String randomUnionB = "";
                int randomSumaUnionA = 0;
                int randomSumaUnionB = 0;

                for (int j = 1; j <= 3; j++) {
                    int randomA = random();
                    int randomB = random();

                    randomUnionA += (randomA + "-");
                    randomUnionB += (randomB + "-");
                    randomSumaUnionA += randomA;
                    randomSumaUnionB += randomB;
                }
                String ganadorPorPartida = randomSumaUnionA > randomSumaUnionB
                        ? "Jugador A"
                        : randomSumaUnionA == randomSumaUnionB
                                ? "Empataron"
                                : "Jugador B";

                modelA.addElement((i + 1) + "): " + randomUnionA);
                modelB.addElement((i + 1) + "): " + randomUnionB);
                modelResultado.addElement((i + 1) + "): " + ganadorPorPartida);
                
                if (randomSumaUnionA == randomSumaUnionB){
                    randomSumaEmpate += 1;
                    continue;
                }

                if (randomSumaUnionA > randomSumaUnionB) CantidadganadorA += 1;
                else CantidadganadorB += 1;
            }
            
            String ganadorFinal = CantidadganadorA > CantidadganadorB
                    ? "Jugador A"
                    : "Jugador B";
            jArea.setText(
                    "Cantidad de veces ganas:" + "\n"
                    + "\tJugador A: " + CantidadganadorA + "\n"
                    + "\tJugador B: " + CantidadganadorB + "\n"
                    + "\tEmpates " + randomSumaEmpate + "\n"
                    + "\tTotal " + (CantidadganadorA + CantidadganadorB + randomSumaEmpate) + "\n"
                    + "El ganador final es el " + ganadorFinal + "\n"
            );

            JListA.setModel(modelA);
            JListB.setModel(modelB);
            JListRes.setModel(modelResultado);
            JOptionPane.showMessageDialog(null, "El ganador final es el : " + ganadorFinal);
            this.changeFire(true);
        } catch (Exception e) {
            this.changeFire(false);
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_CLICKGO

    private void changeFire(boolean change) {
        Color color = new Color(51, 51, 255);
        if (change) {
            color = new Color(153, 51, 255);
        }
        Fire.setBackground(color);
    }

    private int random() {
        int min = 1;
        int max = 13;
        return (int) (Math.random() * (max - min + 1) + min);
    }

    private void CLICKNO(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLICKNO
        String[] emptyList = {};
        JListA.setListData(emptyList);
        JListB.setListData(emptyList);
        JListRes.setListData(emptyList);
        jArea.setText("");
        this.changeFire(false);
    }//GEN-LAST:event_CLICKNO

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numero2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numero2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numero2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numero2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numero2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fire;
    private javax.swing.JList<String> JListA;
    private javax.swing.JList<String> JListB;
    private javax.swing.JList<String> JListRes;
    private javax.swing.JLabel JlabelRotate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea jArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
