/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package S10;

import s09.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/*
 *
 * @author juju
 */
public class numero1 extends javax.swing.JFrame {

    /**
     * Creates new form arreglos
     */
    public numero1() {
        initComponents();
        this.setResizable(false);
        this.setSize(1094, 617);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jCombo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTxtContraB = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLiB = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        JLiA = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        JTxtFaB = new javax.swing.JTextField();
        JTxtContraA = new javax.swing.JTextField();
        JTxtTotalB = new javax.swing.JTextField();
        JTxtFA = new javax.swing.JTextField();
        JTxtTotalA = new javax.swing.JTextField();

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("DejaVu Sans Light", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Resetear");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1094, 587));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("DejaVu Sans Light", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Lanzar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TPG - S11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, 220));

        jPanel4.setBackground(new java.awt.Color(25, 25, 25));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("DejaVu Sans Light", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jCombo1.setBackground(new java.awt.Color(0, 0, 0));
        jCombo1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jCombo1.setForeground(new java.awt.Color(204, 204, 204));
        jCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Z003", 2, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Sample JUJU");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ETC");

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("▪");

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("▪");

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("SansSerif.plain", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("▪");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombo1, 0, 154, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 320));

        JTxtContraB.setEditable(false);
        JTxtContraB.setBackground(new java.awt.Color(51, 51, 51));
        JTxtContraB.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        JTxtContraB.setForeground(new java.awt.Color(204, 204, 204));
        JTxtContraB.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Puntos en contra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(JTxtContraB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 230, 70));

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));

        jLiB.setBackground(new java.awt.Color(51, 51, 51));
        jLiB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador B", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Light", 0, 21), new java.awt.Color(204, 204, 204))); // NOI18N
        jLiB.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLiB.setForeground(new java.awt.Color(204, 204, 204));
        jLiB.setAutoscrolls(false);
        jLiB.setEnabled(false);
        jLiB.setFocusable(false);
        jLiB.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(jLiB);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 240, 320));

        jArea1.setEditable(false);
        jArea1.setBackground(new java.awt.Color(22, 22, 22));
        jArea1.setColumns(10);
        jArea1.setFont(new java.awt.Font("DejaVu Sans", 0, 21)); // NOI18N
        jArea1.setForeground(new java.awt.Color(153, 153, 153));
        jArea1.setRows(5);
        jArea1.setAutoscrolls(false);
        jArea1.setFocusable(false);
        jArea1.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(jArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 300, 550));

        jScrollPane4.setBackground(new java.awt.Color(51, 51, 51));

        JLiA.setBackground(new java.awt.Color(51, 51, 51));
        JLiA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador A", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Light", 0, 21), new java.awt.Color(204, 204, 204))); // NOI18N
        JLiA.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JLiA.setForeground(new java.awt.Color(204, 204, 204));
        JLiA.setEnabled(false);
        JLiA.setFocusable(false);
        JLiA.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane4.setViewportView(JLiA);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 240, 320));

        jLabel7.setFont(new java.awt.Font("SansSerif.plain", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("↔");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        JTxtFaB.setEditable(false);
        JTxtFaB.setBackground(new java.awt.Color(51, 51, 51));
        JTxtFaB.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        JTxtFaB.setForeground(new java.awt.Color(204, 204, 204));
        JTxtFaB.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Puntos a favor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        JTxtFaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtFaBActionPerformed(evt);
            }
        });
        jPanel1.add(JTxtFaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 230, 70));

        JTxtContraA.setEditable(false);
        JTxtContraA.setBackground(new java.awt.Color(51, 51, 51));
        JTxtContraA.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        JTxtContraA.setForeground(new java.awt.Color(204, 204, 204));
        JTxtContraA.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Puntos en contra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        JTxtContraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtContraAActionPerformed(evt);
            }
        });
        jPanel1.add(JTxtContraA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 240, 70));

        JTxtTotalB.setEditable(false);
        JTxtTotalB.setBackground(new java.awt.Color(51, 51, 51));
        JTxtTotalB.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        JTxtTotalB.setForeground(new java.awt.Color(204, 204, 204));
        JTxtTotalB.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Total B", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        JTxtTotalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtTotalBActionPerformed(evt);
            }
        });
        jPanel1.add(JTxtTotalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 230, 70));

        JTxtFA.setEditable(false);
        JTxtFA.setBackground(new java.awt.Color(51, 51, 51));
        JTxtFA.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        JTxtFA.setForeground(new java.awt.Color(204, 204, 204));
        JTxtFA.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Puntos a favor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        JTxtFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtFAActionPerformed(evt);
            }
        });
        jPanel1.add(JTxtFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 240, 70));

        JTxtTotalA.setEditable(false);
        JTxtTotalA.setBackground(new java.awt.Color(51, 51, 51));
        JTxtTotalA.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        JTxtTotalA.setForeground(new java.awt.Color(204, 204, 204));
        JTxtTotalA.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Total A", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Fira Code", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        JTxtTotalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtTotalAActionPerformed(evt);
            }
        });
        jPanel1.add(JTxtTotalA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 240, 70));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int random() {
        int min = 1;
        int max = 8;
        return (int)(Math.random()*(max - min +1) + min);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            DefaultListModel modelA = new DefaultListModel();
            DefaultListModel modelB = new DefaultListModel();
            
            int sumaTotalA = 0;
            int sumaTotalB = 0;
            
            int sumaRestaA = 0;
            int sumaRestaB = 0;
            
            for (int i = 0; i < 20; i++) {
                int currentARandom = this.random();
                int currentBRandom = this.random();
                
                modelA.addElement((i + 1 ) + "): " + currentARandom); 
                modelB.addElement((i + 1 ) + "): " + currentBRandom); 

                sumaTotalA += currentARandom;
                sumaTotalB += currentBRandom;
                
                if(currentARandom == 1) sumaRestaA += 1;
                if(currentBRandom == 1) sumaRestaB += 1;
            }
            
            int totalA = sumaTotalA - sumaRestaA; 
            int totalB = sumaTotalB - sumaRestaB; 
            
            JTxtFA.setText(Integer.toString(sumaTotalA));
            JTxtFaB.setText(Integer.toString(sumaTotalB));
                    
            JLiA.setModel(modelA);
            jLiB.setModel(modelB);
            
            JTxtContraA.setText(Integer.toString(sumaRestaA)); 
            JTxtContraB.setText(Integer.toString(sumaRestaB)); 
            
            JTxtTotalA.setText(Integer.toString(totalA)); 
            JTxtTotalB.setText(Integer.toString(totalB)); 
            
            String ganador = totalA > totalB 
                    ? "Jugador A" : 
                    totalA == totalB ?
                    "Empate" :
                    "Jugador B";
            
            jArea1.setText(
                    """
                    El ganador con una
                    diferencia de """ + Math.abs(totalA - totalB) + "\n" 
                    + "Es el " + ganador
            );
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String[] emptyList = {};
        JLiA.setListData(emptyList);
        jLiB.setListData(emptyList);
        jArea1.setText("");
        JTxtFaB.setText("");
        JTxtFA.setText("");
        JTxtTotalA.setText("");
        JTxtTotalB.setText("");
        JTxtContraA.setText("");
        JTxtContraB.setText("");
        JTxtContraB.requestFocus();
        JTxtTotalB.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JTxtFaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtFaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtFaBActionPerformed

    private void JTxtContraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtContraAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtContraAActionPerformed

    private void JTxtTotalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtTotalBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtTotalBActionPerformed

    private void JTxtFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtFAActionPerformed

    private void JTxtTotalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtTotalAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtTotalAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numero1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JLiA;
    private javax.swing.JTextField JTxtContraA;
    private javax.swing.JTextField JTxtContraB;
    private javax.swing.JTextField JTxtFA;
    private javax.swing.JTextField JTxtFaB;
    private javax.swing.JTextField JTxtTotalA;
    private javax.swing.JTextField JTxtTotalB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea jArea1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jLiB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
